# Generated by Django 4.0.3 on 2022-07-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JcFName', models.CharField(blank=True, max_length=100)),
                ('JcLName', models.CharField(blank=True, max_length=100)),
                ('JcPhone', models.CharField(blank=True, max_length=100)),
                ('JcEmail', models.CharField(blank=True, max_length=100)),
                ('JcAddress', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JcShoes', models.CharField(blank=True, max_length=100)),
                ('JcQuantity', models.CharField(blank=True, max_length=100)),
                ('JcColor', models.CharField(blank=True, max_length=100)),
                ('JcSize', models.CharField(blank=True, max_length=100)),
                ('Jcpayment', models.CharField(blank=True, max_length=100)),
                ('Jcdelivery', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
